##### Menu
menu:
  首页: /
  存档: /archives
  标签: /tags
  分类: /categories
  关于爱: http://love.icerdesign.com
  关于编程: http://icerdesign.com
  关于我: /Hi%EF%BC%8C%E6%88%91%E6%98%AF%E6%91%84%E5%BD%B1%E5%B8%88%E6%B1%90%E4%BA%9A/ 
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- tag
- introduction
- rss
## provide six widgets:category,tag,rss,archive,tagcloud,links.
## modify links in `/layout/_widget/links.ejs`.

#### RSS
rss: atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/hiya.jpg        ## `.svg` and `.png` are recommended,please put image into the theme folder `/pacman/source/img`.
favicon: img/favicon.png   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/pacman/source/img`.     
apple_icon: img/hiya.jpg   ## size:114px*114px,please put image into the theme folder `/pacman/source/img`.

#### Author Avatar Picture
author_img_enable: true ## display author avatar picture
dataURI: false
## if the picture's format is dataURI please set the value to true,otherwise set the value to false.
## convert an image into base 64 data URIs http://websemantics.co.uk/online_tools/image_to_data_uri_convertor/ .
author_img_data: ''
## paste the dataURI in ONE LINE and included it by ''.
author_img: /img/author.jpg ## size:220px*220px.
## if the picture's format is `.png` or `.jpg`  instead of dataURI,you should set the `dataURI` value to false.

#### Font
ShowCustomFont: false
## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/pacman/source/css`.

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Fancybox
fancybox: true 
## if you use gallery post or want use fancybox please set the value to true.
## if you want use fancybox in ANY post please copy the file `fancybox.js`.
## in theme folder `/pacman/scripts` to your hexo blog folder `../scritps`.

#### Author information
author:
  google_plus:    ## eg:116338260303228776998 for https://plus.google.com/u/0/116338260303228776998
  intro_line1: "" ## eg: "Hello ,I'm Larry Page in Google."
  intro_line2: "" ## eg: "This is my blog,believe it or not."
  weibo: lovehiya     ## e.g. 436062867 for http://weibo.com/436062867
  twitter:    ## e.g. yangjiansky for https://twitter.com/yangjiansky
  github:     ## e.g. A-limon for https://github.com/A-limon
  facebook:   ## e.g. yangjian for https://favebook.com/yangjian
  tsina: lovehiya     ## e.g. 1664838973  Your weibo ID,It will be used in share button.

#### Comment
duoshuo: 
  enable: true            ## duoshuo.com
  short_name: hiyaphoto   ## duoshuo short name.

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1501277 your jiathis ID. 
  tsina: ## e.g. 1664838973 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: false
  id:   ## e.g. UA-1766729-8 your google analytics ID.
  site: ## e.g. yangjian.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

#### 51la Analytics
la51_analytics:
  enable: enable
  id: 17278963  ## e.g. 17278963 is your 51la analytics ID.

#### Custom Search
google_cse: 
  enable: false
  cx:  ## e.g. 000561263943549425496:mrzrm0gr4kg your Custom Search ID
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---

#### Standard Search
standard_search: 
  engine: 'baidu'  ## possible enum: false/google/baidu. set to false if you want to hide the default search box

#### fotorama in index page
fotorama:
  enable: false ## true to enable fotorama in index page
  fit: 'contain' ## Can be 'contain', 'cover', 'scaledown', 'none'
  nav: 'thumbs' ## Can be 'dots', 'thumbs', false
  transition: 'slide' ## Can be 'slide', 'crossfade', 'dissolve'
  autoplay: true ## Can be true or false
  loop: true ## Can be true or false
  baseurl: '' ## base url will be prefixed to photo url, both show and thumb
  photos:
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/31.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/31_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/1.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/1_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/2.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/2_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/3.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/3_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/4.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/4_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/5.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/5_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/6.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/6_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/7.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/7_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/8.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/8_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/13.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/13_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/14.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/14_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/15.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/15_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/16.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/16_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/17.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/17_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/18.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/18_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/19.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/19_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/20.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/20_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/22.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/22_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/23.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/23_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/24.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/24_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/25.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/25_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/26.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/26_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/27.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/27_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/28.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/28_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/29.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/29_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/30.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/30_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/32.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/32_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/33.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/33_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/34.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/34_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/36.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/36_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/37.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/37_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/38.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/38_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/39.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/39_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/40.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/40_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/41.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/41_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/42.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/42_thumb.jpg" }
    - { show: "http://hiyaphoto.qiniudn.com/blog/wall/43.jpg", thumb: "http://hiyaphoto.qiniudn.com/blog/wall/43_thumb.jpg" }
## http://fotorama.io/

showUpdateDate: false
